// Local host

###
GET http://localhost:8080/contacts

###
GET http://localhost:8080/contacts/650e600880acea7b1efe23f1

###
GET http://localhost:8080/contacts/650e60e780acea7b1efe23f2

###
GET http://localhost:8080/contacts/650e612f80acea7b1efe23f4

// Render


###
GET https://cse341-8296.onrender.com/contacts

###
GET https://cse341-8296.onrender.com/contacts/650e600880acea7b1efe23f1

###
GET https://cse341-8296.onrender.com/contacts/650e60e780acea7b1efe23f2

###
GET https://cse341-8296.onrender.com/contacts/650e612f80acea7b1efe23f4